pulsar.url=pulsar://pulsar-broker.pulsar.svc.cluster.local:6650
pulsar.connectionsPerBroker=2
pulsar.numIoThreads=4
pulsar.numListenerThreads=2
pulsar.operationTimeout=30
pulsar.keepAliveInterval=30

pulsar.producer.topic=otp
pulsar.producer.sendTimeout=0
pulsar.producer.compressionType=LZ4
pulsar.producer.batchingMaxMessagesPerBatch=100
pulsar.producer.batchingMaxPublishDelay=10
